//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gNowWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gNowWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial view.
        /// </summary>
        public static string btnAerial {
            get {
                return ResourceManager.GetString("btnAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change units.
        /// </summary>
        public static string btnChangeU {
            get {
                return ResourceManager.GetString("btnChangeU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to road view.
        /// </summary>
        public static string btnRoad {
            get {
                return ResourceManager.GetString("btnRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string btnShare {
            get {
                return ResourceManager.GetString("btnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string btnSignOut {
            get {
                return ResourceManager.GetString("btnSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string btnSync {
            get {
                return ResourceManager.GetString("btnSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an application designed by SuperNova in 2014. The main purpose of this App is helping all students around the world to understand better the gravity..
        /// </summary>
        public static string descAbout {
            get {
                return ResourceManager.GetString("descAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above Everest?.
        /// </summary>
        public static string errAltitudeAbove {
            get {
                return ResourceManager.GetString("errAltitudeAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height below Dead Sea?.
        /// </summary>
        public static string errAltitudeBelow {
            get {
                return ResourceManager.GetString("errAltitudeBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have data..
        /// </summary>
        public static string errData {
            get {
                return ResourceManager.GetString("errData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your location. Do you want to activate your GPS?.
        /// </summary>
        public static string errGPS {
            get {
                return ResourceManager.GetString("errGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your GPS..
        /// </summary>
        public static string errGPS2 {
            get {
                return ResourceManager.GetString("errGPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have internet connection..
        /// </summary>
        public static string errInternet {
            get {
                return ResourceManager.GetString("errInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude not valid.
        /// </summary>
        public static string errLatitude {
            get {
                return ResourceManager.GetString("errLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first!.
        /// </summary>
        public static string errLogin {
            get {
                return ResourceManager.GetString("errLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not signed in..
        /// </summary>
        public static string errNoSignIn {
            get {
                return ResourceManager.GetString("errNoSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve previously registered!.
        /// </summary>
        public static string errReg {
            get {
                return ResourceManager.GetString("errReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        public static string errTry {
            get {
                return ResourceManager.GetString("errTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gravity is bigger in: .
        /// </summary>
        public static string gravBigger {
            get {
                return ResourceManager.GetString("gravBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity is the same..
        /// </summary>
        public static string gravSame {
            get {
                return ResourceManager.GetString("gravSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gravity is smaller in: .
        /// </summary>
        public static string gravSmaller {
            get {
                return ResourceManager.GetString("gravSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity vs Altitude.
        /// </summary>
        public static string GvsA {
            get {
                return ResourceManager.GetString("GvsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¹ International Gravity Formula 1967 (IGF).
        /// </summary>
        public static string hypLink1 {
            get {
                return ResourceManager.GetString("hypLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ² Free Air Correction (FAC).
        /// </summary>
        public static string hypLink2 {
            get {
                return ResourceManager.GetString("hypLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string itemEarth {
            get {
                return ResourceManager.GetString("itemEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet (ft).
        /// </summary>
        public static string itemFeet {
            get {
                return ResourceManager.GetString("itemFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial (US).
        /// </summary>
        public static string itemImperial {
            get {
                return ResourceManager.GetString("itemImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupiter.
        /// </summary>
        public static string itemJupiter {
            get {
                return ResourceManager.GetString("itemJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        public static string itemMars {
            get {
                return ResourceManager.GetString("itemMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        public static string itemMercury {
            get {
                return ResourceManager.GetString("itemMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres (m).
        /// </summary>
        public static string itemMetres {
            get {
                return ResourceManager.GetString("itemMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string itemMetric {
            get {
                return ResourceManager.GetString("itemMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        public static string itemMoon {
            get {
                return ResourceManager.GetString("itemMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neptune.
        /// </summary>
        public static string itemNeptune {
            get {
                return ResourceManager.GetString("itemNeptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluto.
        /// </summary>
        public static string itemPluto {
            get {
                return ResourceManager.GetString("itemPluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        public static string itemSaturn {
            get {
                return ResourceManager.GetString("itemSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string itemSun {
            get {
                return ResourceManager.GetString("itemSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus.
        /// </summary>
        public static string itemUranus {
            get {
                return ResourceManager.GetString("itemUranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus.
        /// </summary>
        public static string itemVenus {
            get {
                return ResourceManager.GetString("itemVenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string lblAltitude {
            get {
                return ResourceManager.GetString("lblAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to altitude.
        /// </summary>
        public static string lblAltitude1 {
            get {
                return ResourceManager.GetString("lblAltitude1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Syncing.
        /// </summary>
        public static string lblASync {
            get {
                return ResourceManager.GetString("lblASync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My gravity now is: .
        /// </summary>
        public static string lblBody1 {
            get {
                return ResourceManager.GetString("lblBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , checking your one with Gravity Now! How about you?.
        /// </summary>
        public static string lblBody2 {
            get {
                return ResourceManager.GetString("lblBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one.
        /// </summary>
        public static string lblChoose {
            get {
                return ResourceManager.GetString("lblChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formulas used by this App are based on the International Gravity Formula 1967 (IGF)¹ which determines the gravity from the position of latitude, and the Free Air Correction (FAC)² which corrects for height above sea level..
        /// </summary>
        public static string lblFormula1 {
            get {
                return ResourceManager.GetString("lblFormula1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string lblFormula10 {
            get {
                return ResourceManager.GetString("lblFormula10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above sea level is a value in metres or feet. If you do not know the height above sea level you should be able to obtain it from your national geological survey maps..
        /// </summary>
        public static string lblFormula11 {
            get {
                return ResourceManager.GetString("lblFormula11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string lblFormula2 {
            get {
                return ResourceManager.GetString("lblFormula2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● g = Theoretical local gravity.
        /// </summary>
        public static string lblFormula3 {
            get {
                return ResourceManager.GetString("lblFormula3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● IGF = International Gravity Formula.
        /// </summary>
        public static string lblFormula4 {
            get {
                return ResourceManager.GetString("lblFormula4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● FAC = Free Air Correction.
        /// </summary>
        public static string lblFormula5 {
            get {
                return ResourceManager.GetString("lblFormula5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● Φ = Latitude.
        /// </summary>
        public static string lblFormula6 {
            get {
                return ResourceManager.GetString("lblFormula6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● h = Height relative to sea level.
        /// </summary>
        public static string lblFormula7 {
            get {
                return ResourceManager.GetString("lblFormula7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string lblFormula8 {
            get {
                return ResourceManager.GetString("lblFormula8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position relative to the equator in decimal degrees. Latitude can only be specified between -90° and 90°. You can determine the latitude position by going to Google Maps and right clicking on the required location and then selecting “Drop LatLng Marker” which will display the decimal latitude value first before the longitude value..
        /// </summary>
        public static string lblFormula9 {
            get {
                return ResourceManager.GetString("lblFormula9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gravity.
        /// </summary>
        public static string lblGravity {
            get {
                return ResourceManager.GetString("lblGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity:.
        /// </summary>
        public static string lblGravity2 {
            get {
                return ResourceManager.GetString("lblGravity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth&apos;s gravity measured by NASA&apos;s GRACE mission, showing deviations from the theoretical gravity of an idealized smooth Earth, the so-called earth ellipsoid. Red shows the areas where gravity is stronger than the smooth, standard value, and blue reveals areas where gravity is weaker. (Animated version).
        /// </summary>
        public static string lblGravityCDesc {
            get {
                return ResourceManager.GetString("lblGravityCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity, is a natural phenomenon by which all physical bodies attract each other. It is most commonly recognized and experienced as the agent that gives weight to physical objects, and causes physical objects to fall toward the ground when dropped from a height..
        /// </summary>
        public static string lblGravityDesc {
            get {
                return ResourceManager.GetString("lblGravityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings.
        /// </summary>
        public static string lblGreeting {
            get {
                return ResourceManager.GetString("lblGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string lblLatitude {
            get {
                return ResourceManager.GetString("lblLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude.
        /// </summary>
        public static string lblLatitude1 {
            get {
                return ResourceManager.GetString("lblLatitude1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string lblLongitude {
            get {
                return ResourceManager.GetString("lblLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude.
        /// </summary>
        public static string lblLongitude1 {
            get {
                return ResourceManager.GetString("lblLongitude1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Networks.
        /// </summary>
        public static string lblSocial {
            get {
                return ResourceManager.GetString("lblSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, check your gravity!.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string lblUnits {
            get {
                return ResourceManager.GetString("lblUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit us.
        /// </summary>
        public static string lblVisit {
            get {
                return ResourceManager.GetString("lblVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of decimal places (calculator).
        /// </summary>
        public static string maximumC {
            get {
                return ResourceManager.GetString("maximumC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of decimal places (gravity).
        /// </summary>
        public static string maximumG {
            get {
                return ResourceManager.GetString("maximumG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what is gravity?.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string menuProfile {
            get {
                return ResourceManager.GetString("menuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gravity was successfully registered, thanks!.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your information was successfully registered, thanks!.
        /// </summary>
        public static string successFull {
            get {
                return ResourceManager.GetString("successFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string titleAbout {
            get {
                return ResourceManager.GetString("titleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculator.
        /// </summary>
        public static string titleCalculator {
            get {
                return ResourceManager.GetString("titleCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparative.
        /// </summary>
        public static string titleComparative {
            get {
                return ResourceManager.GetString("titleComparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definition.
        /// </summary>
        public static string titleDefinition {
            get {
                return ResourceManager.GetString("titleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formula.
        /// </summary>
        public static string titleFormula {
            get {
                return ResourceManager.GetString("titleFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gravity change.
        /// </summary>
        public static string titleGravityC {
            get {
                return ResourceManager.GetString("titleGravityC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my locations.
        /// </summary>
        public static string titleLocations {
            get {
                return ResourceManager.GetString("titleLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string titleNow {
            get {
                return ResourceManager.GetString("titleNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string titleOptions {
            get {
                return ResourceManager.GetString("titleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string titleProfile {
            get {
                return ResourceManager.GetString("titleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        public static string titleShare {
            get {
                return ResourceManager.GetString("titleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string titleThanks {
            get {
                return ResourceManager.GetString("titleThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS GRAVITY?.
        /// </summary>
        public static string titleWGravity {
            get {
                return ResourceManager.GetString("titleWGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name:.
        /// </summary>
        public static string txtFullName {
            get {
                return ResourceManager.GetString("txtFullName", resourceCulture);
            }
        }
    }
}
